---
name: Prettier

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Can the code be prettier? ðŸ¤”
    runs-on: ubuntu-latest
    # workflow_dispatch always lets you select the branch ref, even though in this case we only ever want to run the action on `main` this we need an if check
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write # for gr2m/create-or-update-pull-request-action to create a PR
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --ignore-scripts --only-dev
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: node_modules/.cache/prettier/.prettier-cache
          key: prettier-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.gitignore') }}
      - run: npm run format
      - run: git restore .github/workflows
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PR_TOKEN }}
        with:
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          branch: actions/prettier-if-needed
          title: 'chore(prettier): fix unformatted files'
          body: A robot ran `npm run format` and made this PR.
          commit-message: 'chore(prettier): ðŸ¤– âœ¨'
          labels: automation
